# Generated by Django 4.1.1 on 2022-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectCode', models.CharField(max_length=64)),
                ('subjectName', models.CharField(max_length=64)),
                ('semester', models.CharField(max_length=64)),
                ('year', models.CharField(max_length=64)),
                ('quota', models.CharField(max_length=64)),
            ],
        ),
    ]
