# Generated by Django 4.1.1 on 2022-09-10 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='status',
        ),
    ]
