# Generated by Django 4.1.1 on 2022-09-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_subject_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='quota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='semester',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(),
        ),
    ]
