# Generated by Django 4.1.1 on 2022-09-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0005_alter_subject_quota_alter_subject_semester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="detail",
            field=models.CharField(default="", max_length=64),
        ),
    ]
